analyzer:
  errors:
    unrelated_type_equality_checks: ignore
    library_private_types_in_public_api: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    avoid_print: false  
    prefer_single_quotes: true 
