name: notes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

module:
  androidX: true


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.15.0
  modal_progress_hud_nsn: ^0.5.1
  go_router: ^16.0.0
  shared_preferences: ^2.5.2
  share_plus: ^11.0.0
  shimmer: ^3.0.0
  path_provider: ^2.1.4
  animated_expandable_fab: ^0.0.3
  url_launcher: ^6.3.2
  super_clipboard: ^0.8.24
  intl: ^0.20.2
  intl_utils: ^2.8.7
  quill_html_editor_v2: ^2.2.10
  bloc: ^9.0.0
  hydrated_bloc: ^10.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_quill: ^11.4.1
  flutter_keyboard_visibility_temp_fork: ^0.1.1
  flutter_quill_extensions: ^11.0.0
  flutter_colorpicker: ^1.1.0
  flutter_screenutil: ^5.9.3
  flutter_localization: ^0.3.1
  flutter_secure_storage: ^9.2.4
  flutter_cache_manager: ^3.4.1
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/notes_logo.png"
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
